server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  application:
    name: trego-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
    time-zone: UTC
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

# Firebase Configuration
firebase:
  project-id: ${FIREBASE_PROJECT_ID:trego-fb4f3}
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:./config/firebase-credentials.json}
  storage-bucket: ${FIREBASE_STORAGE_BUCKET:trego-fb4f3.appspot.com}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-change-in-production}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

# External API Configuration
openai:
  api-key: ${OPENAI_API_KEY:}
  model: ${OPENAI_MODEL:gpt-3.5-turbo}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# Logging
logging:
  level:
    com.trego: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/trego-backend.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized